# Generated by Django 2.2.6 on 2019-10-25 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('europepmc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='name',
            new_name='title',
        ),
    ]
