# Generated by Django 2.2.6 on 2019-10-25 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('europepmc', '0002_auto_20191025_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='biobank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='europepmc.Biobank'),
            preserve_default=False,
        ),
    ]
