# Generated by Django 2.2.6 on 2019-10-30 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('europepmc', '0005_auto_20191029_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='europepmc.Publication'),
        ),
    ]
