# Generated by Django 2.2.6 on 2019-10-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europepmc', '0006_auto_20191030_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
    ]
